### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered while running MLE + RL training

### ISSUE THREAD

**Issue by ranjeetds** [rohithreddy024/Text-Summarizer-Pytorch#23]
I am getting following error while running MLE + RL training

`Traceback (most recent call last):
  File "train.py", line 270, in <module>
    train_processor.trainIters()
  File "train.py", line 238, in trainIters
    mle_loss, r = self.train_one_batch(batch, iter)
  File "train.py", line 202, in train_one_batch
    mle_loss = self.train_batch_MLE(enc_out, enc_hidden, enc_padding_mask, context, extra_zeros, enc_batch_extend_vocab, batch)
  File "train.py", line 80, in train_batch_MLE
    use_gound_truth = get_cuda((T.rand(len(enc_out)) > 0.25)).long()                        #Probabilities indicating whether to use ground truth labels instead of previous decoded tokens
  File "/home/exa00117/Project/textSummerization/rnn/Text-Summarizer-Pytorch-master/train_util.py", line 7, in get_cuda
    tensor = tensor.cuda()`

Could you please help resolve it?

**Comment by ranjeetds** [comment]
#3 resolves the issue
