### ISSUE TITLE
RL mode requires much more GPU memory

### ISSUE THREAD

**Issue by xcfcode** [rohithreddy024/Text-Summarizer-Pytorch#6]
I find one empty GPU, there is no more error, however, it still confused me that why RL mode requires much more memory?

---

Hi, Thanks for your excellent job, But when I start RL training, some errors occurs as follows"
```
Traceback (most recent call last):
  File "train.py", line 316, in <module>
    train_processor.train_iters()
  File "train.py", line 274, in train_iters
    mle_loss, r = self.train_one_batch(batch, iter)
  File "train.py", line 238, in train_one_batch
    enc_batch_extend_vocab, batch.art_oovs, greedy=True)
  File "train.py", line 164, in train_batch_rl
    sum_temporal_srcs, prev_s)
  File "/users4/xiachongfeng/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/users4/xiachongfeng/Summ_entail/model.py", line 142, in forward
    ct_e, attn_dist, sum_temporal_srcs = self.enc_attention(st_hat, enc_out, enc_padding_mask, sum_temporal_srcs)
  File "/users4/xiachongfeng/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/users4/xiachongfeng/Summ_entail/model.py", line 52, in forward
    et = self.W_h(h)  # bs,n_seq,2*n_hid
  File "/users4/xiachongfeng/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/users4/xiachongfeng/anaconda3/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/users4/xiachongfeng/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1026, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: out of memory
```
Could you please help me?

**Comment by rohithreddy024** [comment]
If the arguments while running `train.py` are `--train_mle=yes --train_rl=yes`, then the model performs both MLE training and RL training simultaneously and thus constructs computational graphs corresponding to both the training processes at the same time. Hence, RL training requires more memory compared to MLE training alone. If you want to solve out of memory error, try reducing the value of `batch_size` variable in `data_util/config.py`

**Comment by xcfcode** [comment]
Thanks a lot!
